import pytest

from leapp import reporting
from leapp.libraries.actor import checknetworkmanagerunmanaged
from leapp.libraries.common.testutils import create_report_mocked, logger_mocked
from leapp.libraries.stdlib import api

# Verbatim from a USERLAND-AUTO CL8 nopanel guest (template 6663,
# one-context-6.4.0-1.el8). Written at boot by one-context's
# loc-10-network.d/functions::nm_disable(), hence the marker comment and the
# fact that no RPM owns it.
RUNTIME_GENERATED_OVERRIDE = (
    '# Generated by one-context\n'
    '\n'
    '# NOTE: NetworkManager was dynamically disabled by OpenNebula\n'
    '# contextualization scripts because interfaces are managed by\n'
    '# different network service!\n'
    '\n'
    '[keyfile]\n'
    'unmanaged-devices=*\n'
)


def _seed(tmp_path, files):
    conf_d = tmp_path / 'conf.d'
    conf_d.mkdir()
    for name, content in files.items():
        (conf_d / name).write_text(content)
    return str(conf_d)


def _patch(monkeypatch, conf_d_path, target_version='9'):
    monkeypatch.setattr(checknetworkmanagerunmanaged, 'NM_CONFD_DIR', conf_d_path)
    monkeypatch.setattr(api, 'current_logger', logger_mocked())
    monkeypatch.setattr(reporting, 'create_report', create_report_mocked())
    monkeypatch.setattr(
        checknetworkmanagerunmanaged, 'get_target_major_version',
        lambda: target_version,
    )


def test_runtime_generated_override_inhibits(monkeypatch, tmp_path):
    conf_d = _seed(tmp_path, {'50-unmanaged-devices.conf': RUNTIME_GENERATED_OVERRIDE})
    _patch(monkeypatch, conf_d)

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 1
    fields = reporting.create_report.report_fields
    assert fields['severity'] == 'high'
    assert 'inhibitor' in fields['groups']
    assert conf_d + '/50-unmanaged-devices.conf' in fields['summary']
    assert 'remediations' in fields['detail']


def test_admin_authored_override_also_inhibits(monkeypatch, tmp_path):
    """Provenance is irrelevant now that nothing is modified: a hand-written
    wildcard override strands the host just as effectively, and the operator
    is the one who decides what to do about it."""
    conf_d = _seed(tmp_path, {'99-admin.conf': '[keyfile]\nunmanaged-devices=*\n'})
    _patch(monkeypatch, conf_d)

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 1
    assert conf_d + '/99-admin.conf' in reporting.create_report.report_fields['summary']


def test_no_report_when_target_is_el8(monkeypatch, tmp_path):
    """CL8 still ships network-scripts, so network.service brings the
    interfaces up and the override is survivable. Inhibiting a 7->8 upgrade
    over it would be a false positive."""
    conf_d = _seed(tmp_path, {'50-unmanaged-devices.conf': RUNTIME_GENERATED_OVERRIDE})
    _patch(monkeypatch, conf_d, target_version='8')

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 0


def test_missing_confd_directory(monkeypatch, tmp_path):
    _patch(monkeypatch, str(tmp_path / 'absent'))
    checknetworkmanagerunmanaged.process()
    assert reporting.create_report.called == 0


@pytest.mark.parametrize('content', [
    '[keyfile]\nunmanaged-devices=mac:aa:bb:cc:dd:ee:ff\n',
    '[keyfile]\nunmanaged-devices=interface-name:eth1\n',
    '[keyfile]\nplugins=ifcfg-rh\n',
    '[main]\ndns=none\nno-auto-default=*\n',
    '# unmanaged-devices=*\n',
    '',
])
def test_non_wildcard_content_is_ignored(monkeypatch, tmp_path, content):
    conf_d = _seed(tmp_path, {'10-other.conf': content})
    _patch(monkeypatch, conf_d)

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 0


def test_non_conf_files_are_skipped(monkeypatch, tmp_path):
    conf_d = _seed(tmp_path, {
        'README.txt': '[keyfile]\nunmanaged-devices=*\n',
        '50-unmanaged-devices.conf.disabled': '[keyfile]\nunmanaged-devices=*\n',
    })
    _patch(monkeypatch, conf_d)

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 0


def test_multiple_overrides_listed_in_one_report(monkeypatch, tmp_path):
    conf_d = _seed(tmp_path, {
        '50-unmanaged-devices.conf': RUNTIME_GENERATED_OVERRIDE,
        '99-extra.conf': '[keyfile]\nunmanaged-devices=*\n',
        '10-fine.conf': '[main]\ndns=default\n',
    })
    _patch(monkeypatch, conf_d)

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 1
    summary = reporting.create_report.report_fields['summary']
    assert conf_d + '/50-unmanaged-devices.conf' in summary
    assert conf_d + '/99-extra.conf' in summary
    assert '10-fine.conf' not in summary


@pytest.mark.parametrize('spacing', [
    'unmanaged-devices=*',
    '  unmanaged-devices=*  ',
    'unmanaged-devices = *',
    'unmanaged-devices=  *',
])
def test_wildcard_spacing_variants_match(monkeypatch, tmp_path, spacing):
    conf_d = _seed(tmp_path, {'50-x.conf': '[keyfile]\n{0}\n'.format(spacing)})
    _patch(monkeypatch, conf_d)

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 1


def test_unreadable_file_does_not_raise(monkeypatch, tmp_path):
    conf_d = _seed(tmp_path, {'50-x.conf': RUNTIME_GENERATED_OVERRIDE})
    _patch(monkeypatch, conf_d)

    def raising_open(*args, **kwargs):
        raise IOError('permission denied')
    monkeypatch.setattr(checknetworkmanagerunmanaged, 'open', raising_open, raising=False)

    checknetworkmanagerunmanaged.process()

    assert reporting.create_report.called == 0
