%global leapp_datadir %{_datadir}/leapp-repository
%global repositorydir %{leapp_datadir}/repositories
%global custom_repositorydir %{leapp_datadir}/custom-repositories

%define leapp_repo_deps  10

%if 0%{?rhel} == 7
    %define leapp_python_sitelib %{python2_sitelib}
    %define lpr_name leapp-upgrade-el7toel8
%else
    %define leapp_python_sitelib %{python3_sitelib}
    %define lpr_name leapp-upgrade-el8toel9

    # This drops autogenerated deps on
    #    - /usr/libexec/platform-python  (rhel-8 buildroot)
    #    - /usr/bin/python3.x (epel-8 buildroot)
    #    - python(abi) = 3.x
    # Each of these lead into the removal of leapp rpms as python is changed between
    # major versions of RHEL
    %global __requires_exclude ^python\\(abi\\) = 3\\..+|/usr/libexec/platform-python|/usr/bin/python.*
%endif


# TODO: not sure whether it's required nowadays. Let's check it and drop
# the whole block if not.
%if 0%{?rhel} == 7
# Defining py_byte_compile macro because it is not defined in old rpm (el7)
# Only defined to python2 since python3 is not used in RHEL7
%{!?py_byte_compile: %global py_byte_compile py2_byte_compile() {\
    python_binary="%1"\
    bytecode_compilation_path="%2"\
    find $bytecode_compilation_path -type f -a -name "*.py" -print0 | xargs -0 $python_binary -c 'import py_compile, sys; [py_compile.compile(f, dfile=f.partition("$RPM_BUILD_ROOT")[2]) for f in sys.argv[1:]]' || :\
    find $bytecode_compilation_path -type f -a -name "*.py" -print0 | xargs -0 $python_binary -O -c 'import py_compile, sys; [py_compile.compile(f, dfile=f.partition("$RPM_BUILD_ROOT")[2]) for f in sys.argv[1:]]' || :\
}\
py2_byte_compile "%1" "%2"}
%endif


# We keeps the leapp-repository name for the component, however we do not plan
# to create such an rpm. Instead, we are going to introduce new naming for
# RHEL 8+ packages to be consistent with other leapp projects in future.

Name:           leapp-repository
Version:        0.20.0
Release:        11%{?dist}.cloudlinux
Summary:        Repositories for leapp

License:        ASL 2.0
URL:            https://oamg.github.io/leapp/
Source0:        https://github.com/oamg/%{name}/archive/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source1:        deps-pkgs.tar.gz

# NOTE: Our packages must be noarch. Do no drop this in any way.
BuildArch:      noarch

### PATCHES HERE
# Patch0001:    filename.patch


%description
%{summary}


# This is the real RPM with the leapp repositories content
%package -n %{lpr_name}
Summary: Leapp repositories for the in-place upgrade

%if 0%{?rhel} == 7
######### RHEL 7 ############
BuildRequires:  python-devel
Requires:       python2-leapp

# We should not drop this on RHEL 7 because of the compatibility reasons
Obsoletes:      leapp-repository-data <= 0.6.1
Provides:       leapp-repository-data <= 0.6.1

# Former leapp subpackage that is part of the sos package since RHEL 7.8
Obsoletes:      leapp-repository-sos-plugin <= 0.9.0

# Set the conflict to be sure this RPM is not upgraded automatically to
# the one from the target (upgraded) RHEL. The RPM has to stay untouched
# during the whole IPU process.
# The manual removal of the RPM is required after the IPU
Conflicts:      leapp-upgrade-el8toel9

%else
######### RHEL 8 ############
BuildRequires:  python3-devel
Requires:       python3-leapp

# Same as the conflict above - we want to be sure our packages are untouched
# during the whole IPU process
Conflicts:      leapp-upgrade-el7toel8

%endif

# cln-switch-channel was provided by rhn-client-tools 2.x to support the
# CLN-side channel switch. rhn-client-tools 3.0+ removes both the binary and
# the Provide as part of the no-auth migration. The actor that invokes it
# (switchclnchannel) is gated on is_cln_package_channel_active() (CLOS-4056),
# so on no-auth systems it never runs and the missing binary is harmless. On
# CLN-active systems rhn-client-tools 2.x is installed, supplying the binary
# at runtime, so the install-time pin was redundant. Drop it to allow
# rhn-client-tools 3.0+ on the same system as leapp-upgrade-el8toel9
# (otherwise leapp_qa Run #54 dnf_transaction_check fails: rhn-client-tools
# 3.x cannot be installed alongside an RPM that requires
# cln-switch-channel = 2).

# IMPORTANT: every time the requirements are changed, increment number by one
# - same for Provides in deps subpackage
Requires:       leapp-repository-dependencies = %{leapp_repo_deps}

# IMPORTANT: this is capability provided by the leapp framework rpm.
# Check that 'version' instead of the real framework rpm version.
Requires:       leapp-framework >= 6.0, leapp-framework < 7

# Since we provide sub-commands for the leapp utility, we expect the leapp
# tool to be installed as well.
Requires:       leapp >= 0.17.0

# Used to determine RHEL version of a given target RHEL installation image -
# uncompressing redhat-release package from the ISO.
Requires:   cpio

# The leapp-repository rpm is renamed to %%{lpr_name}
Obsoletes:      leapp-repository < 0.14.0-%{release}
Provides:       leapp-repository = %{version}-%{release}

# Provide "leapp-upgrade" for the user convenience. Users will be pointed
# to install "leapp-upgrade" in the official docs.
Provides:       leapp-upgrade = %{version}-%{release}

# Provide leapp-commands so the framework could refer to them when customers
# do not have installed particular leapp-repositories
Provides:       leapp-command(answer)
Provides:       leapp-command(preupgrade)
Provides:       leapp-command(upgrade)
Provides:       leapp-command(rerun)
Provides:       leapp-command(list-runs)


%description -n %{lpr_name}
Leapp repositories for the in-place upgrade to the next major version
of the Red Hat Enterprise Linux system.


# This metapackage should contain all RPM dependencies excluding deps on *leapp*
# RPMs. This metapackage will be automatically replaced during the upgrade
# to satisfy dependencies with RPMs from target system.
%package -n %{lpr_name}-deps
Summary:    Meta-package with system dependencies of %{lpr_name} package

# The package has been renamed, so let's obsoletes the old one
Obsoletes:      leapp-repository-deps < 0.14.0-%{release}

# The package was updated with new version of pes files
Conflicts:      leapp-data-cloudlinux < 0.3-8

# IMPORTANT: every time the requirements are changed, increment number by one
# - same for Requires in main package
Provides:  leapp-repository-dependencies = %{leapp_repo_deps}
##################################################
# Real requirements for the leapp-repository HERE
##################################################
Requires:   dnf >= 4
Requires:   pciutils

# required to be able to format disk images with XFS file systems (default)
Requires:   xfsprogs

# required to be able to format disk images with Ext4 file systems
# NOTE: this is not happening by default, but we can expact that many customers
# will want to / need to do this - especially on RHEL 7 now. Adding this deps
# as the best trade-off to resolve this problem.
Requires:   e2fsprogs

%if 0%{?rhel} && 0%{?rhel} == 7
# Required to gather system facts about SELinux
Requires:   libselinux-python
Requires:   python-pyudev
# required by SELinux actors
Requires:   policycoreutils-python
# Required to fetch leapp data
Requires:   python-requests

%else
############# RHEL 8 dependencies (when the source system is RHEL 8) ##########
# systemd-nspawn utility
Requires:   systemd-container
Requires:   python3-pyudev
# Required to fetch leapp data
Requires:   python3-requests
# Required because the code is kept Py2 & Py3 compatible
Requires:   python3-six
# required by SELinux actors
Requires:   policycoreutils-python-utils
# required by systemfacts, and several other actors
Requires:   procps-ng
Requires:   kmod
# since RHEL 8+ dracut does not have to be present on the system all the time
# and missing dracut could be killing situation for us :)
Requires:   dracut

# Required to scan NetworkManagerConnection (e.g. to recognize secrets)
# NM is requested to be used on RHEL 8+ systems
Requires:   NetworkManager-libnm
Requires:   python3-gobject-base

%endif
##################################################
# end requirement
##################################################


%description -n %{lpr_name}-deps
%{summary}


%prep
%setup -n %{name}-%{version}
%setup -q  -n %{name}-%{version} -D -T -a 1

# APPLY PATCHES HERE
# %%patch0001 -p1


%build
%if 0%{?rhel} == 7
cp -a leapp*deps*el8.noarch.rpm repos/system_upgrade/el7toel8/files/bundled-rpms/
%else
cp -a leapp*deps*el9.noarch.rpm repos/system_upgrade/el8toel9/files/bundled-rpms/
%endif


%install
install -m 0755 -d %{buildroot}%{custom_repositorydir}
install -m 0755 -d %{buildroot}%{repositorydir}
cp -r repos/* %{buildroot}%{repositorydir}/
install -m 0755 -d %{buildroot}%{_sysconfdir}/leapp/repos.d/
install -m 0755 -d %{buildroot}%{_sysconfdir}/leapp/transaction/
install -m 0755 -d %{buildroot}%{_sysconfdir}/leapp/files/
install -m 0644 etc/leapp/transaction/* %{buildroot}%{_sysconfdir}/leapp/transaction

# install CLI commands for the leapp utility on the expected path
install -m 0755 -d %{buildroot}%{leapp_python_sitelib}/leapp/cli/
cp -r commands %{buildroot}%{leapp_python_sitelib}/leapp/cli/
rm -rf %{buildroot}%{leapp_python_sitelib}/leapp/cli/commands/tests

# Remove irrelevant repositories - We don't want to ship them for the particular
# RHEL version
%if 0%{?rhel} == 7
rm -rf %{buildroot}%{repositorydir}/system_upgrade/el8toel9
%else
rm -rf %{buildroot}%{repositorydir}/system_upgrade/el7toel8
%endif

# remove component/unit tests, Makefiles, ... stuff that related to testing only
rm -rf %{buildroot}%{repositorydir}/common/actors/testactor
find %{buildroot}%{repositorydir}/common -name "test.py" -delete
rm -rf `find %{buildroot}%{repositorydir} -name "tests" -type d`
find %{buildroot}%{repositorydir} -name "Makefile" -delete

for DIRECTORY in $(find  %{buildroot}%{repositorydir}/  -mindepth 1 -maxdepth 1 -type d);
do
    REPOSITORY=$(basename $DIRECTORY)
    echo "Enabling repository $REPOSITORY"
    ln -s  %{repositorydir}/$REPOSITORY  %{buildroot}%{_sysconfdir}/leapp/repos.d/$REPOSITORY
done;

# __python2 could be problematic on systems with Python3 only, but we have
# no choice as __python became error on F33+:
#   https://fedoraproject.org/wiki/Changes/PythonMacroError
%if 0%{?rhel} == 7
%py_byte_compile %{__python2} %{buildroot}%{repositorydir}/*
%else
%py_byte_compile %{__python3} %{buildroot}%{repositorydir}/*
%endif


%files -n %{lpr_name}
%doc README.md
%license LICENSE
%dir %{_sysconfdir}/leapp/transaction
%dir %{_sysconfdir}/leapp/files
%dir %{leapp_datadir}
%dir %{repositorydir}
%dir %{custom_repositorydir}
%dir %{leapp_python_sitelib}/leapp/cli/commands
%{_sysconfdir}/leapp/repos.d/*
%{_sysconfdir}/leapp/transaction/*
%{repositorydir}/*
%{leapp_python_sitelib}/leapp/cli/commands/*


%files -n %{lpr_name}-deps
# no files here


# DO NOT TOUCH SECTION BELOW IN UPSTREAM
%changelog
* Tue Aug 11 2026 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.20.0-11.cloudlinux
- CLOS-4518: Fix systemd timers that replace a cron job on the new system being left disabled after the upgrade
- CLOS-6809: Fix the upgrade being blocked on servers running MySQL Governor with MariaDB 11.4 or 11.8, where the installed database version was reported in a form that the cl-mysql repository check did not recognise
- Determine the database module to enable from the configured cl-mysql repository, so that newly released CloudLinux MySQL and MariaDB versions are upgraded correctly without waiting for a Leapp update

* Thu Aug 06 2026 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.20.0-10.cloudlinux
- CLOS-2132: Warn before the upgrade when the PostgreSQL configuration would keep the database from starting on the new system, and spell out the migration steps to run afterwards
- CLOS-3716: Stop the upgrade when the target repositories offer a kernel newer than the rest of the target system, which could leave LVE unusable after the reboot
- CLOS-4330: Stop the upgrade when NetworkManager is configured to manage no devices, which would leave the upgraded system without networking
- CLOS-4726: Fix the upgrade failing to install the CloudLinux 8 release package because of a conflict with the CloudLinux 7 CLN client tools
- CLOS-6840: Fix an unusable MariaDB repository being generated for upstream MariaDB URLs, and explain why an unsupported MariaDB version blocks the upgrade

* Sun May 17 2026 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.20.0-9.cloudlinux
- CLOS-2598: Fix the lua-cjson package conflicting with its own upgrade during CloudLinux 7 to CloudLinux 8 upgrades
- CLOS-2816: Fix the upgrade failing while trying to create an oversized scratch disk image
- CLOS-2842: Fix creation of the upgrade boot entry on systems with a hybrid BIOS and UEFI boot layout
- CLOS-3465: Stop the upgrade when '_netdev' mount points are present in /etc/fstab, because they cannot be mounted after the first reboot
- CLOS-3960: Fix CLN plugin activation failing on the first boot after a CloudLinux 7 to CloudLinux 8 upgrade
- CLOS-4056: Support upgrades on systems that use CloudLinux package repositories without CLN registration, in addition to CLN-registered systems
- CLOS-4332: Stop reporting CloudLinux and AlmaLinux repositories as unknown to Leapp when they are in fact mapped
- Accept '--non-interactive' as an alias for the 'leapp upgrade --nowarn' option
- Assorted internal maintenance and packaging improvements

* Wed Apr 22 2026 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.20.0-8.cloudlinux
- CLOS-3762: Fix MySQL and MariaDB module stream selection for CloudLinux MariaDB 10.11 and make the installed database version detection more reliable
- CLOS-3827: Add a missing Imunify package signature to the list of trusted signatures
- CLOS-3828: Fix the set of target repositories being incomplete when more than one repository mapping is available
- CLOS-3833: Fix mysqlclient and cl-MySQL/cl-MariaDB packages not being upgraded when their repositories are disabled
- CLOS-4259: Fix a Python 2.7 incompatibility on CloudLinux 7, and stop the upgrade when the cl-mysql repository file does not match the installed database
- Stop the upgrade when the database type reported by MySQL Governor does not match the installed packages
- Stop the upgrade, instead of only warning, when a system with a control panel does not match memory requirements

* Sun Aug 17 2025 Oleksandr Shyshatskyi <oshyshatskyi@cloudlinux.com> - 0.20.0-7.cloudlinux
- CLOS-3468: Support CloudLinux 8 to CloudLinux 9 upgrades on systems with cl-mysql repositories, and warn when an unsupported MariaDB repository URL is configured
- CLOS-3489: Add cl-MySQL 8.4 and cl-MariaDB 11.4 to the database package mappings
- CLOS-3490: Fix upgrades on systems that use the upstream MariaDB repository
- Stop the upgrade when an outdated MariaDB version is installed, and explain what has to be done before upgrading

* Fri May 23 2025 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.20.0-6.cloudlinux
- CLOS-3344: Detect leftover package repository files created by cldeploy and handle them during the upgrade

* Thu Feb 27 2025 Oleksandr Shyshatskyi <oshyshatskyi@cloudlinux.com> - 0.20.0-5.cloudlinux
- CLOS-3202: Replace the rhn-client-tools version check with a package dependency
- CLOS-3205: Fix errors raised by the package conflict resolution step during CloudLinux 8 to CloudLinux 9 upgrades
- CLOS-3211: Switch the CLN channel only inside the upgrade container during preupgrade checks, leaving the running system untouched
- CLOS-3224: Fix repository file parsing failing on CloudLinux 8
- CLOS-3230: Refresh EPEL repositories that still point at the previous release after the upgrade, which could make the upgrade try to remove systemd
- CLOS-3233: Fix mirror pinning not working during CloudLinux 8 to CloudLinux 9 upgrades
- CLOS-3241: Create a marker file when the upgrade completes so that tooling can reliably detect the end of the process

* Thu Feb 06 2025 Oleksandr Shyshatskyi <oshyshatskyi@cloudlinux.com> - 0.20.0-4.cloudlinux
- CLOS-3200: Fix 'leapp preupgrade' failing with an 'unable to open database file' error

* Mon Feb 03 2025 Oleksandr Shyshatskyi <oshyshatskyi@cloudlinux.com> - 0.20.0-3.cloudlinux
- CLOS-3068: Report failed DNF commands as upgrade errors so that control panel tooling notices a failed preupgrade instead of continuing
- CLOS-3187: Add support for upgrades from CloudLinux OS 8 to CloudLinux OS 9

* Wed Sep 11 2024 Oleksandr Shyshatskyi <oshyshatskyi@cloudlinux.com> - 0.20.0-2.cloudlinux
- CLOS-2879: Require the versions of leapp and leapp-data-cloudlinux that contain the corrected alt-php package mappings

* Fri Aug 30 2024 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.20.0-1.cloudlinux
- CLOS-2615: Rebase the CloudLinux upgrade code onto upstream leapp-repository 0.20.0
- CLOS-2786: Fix partition layout detection failing on systems whose boot partition is on a software RAID
- Report the detected OS version together with the 'unsupported OS' inhibitor to make it easier to diagnose

* Thu Jul 04 2024 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.16.0-10.cloudlinux
- CLOS-2610: Add upgrade inhibitors for outdated GRUB and insufficient space in boot disk embedding area
- CLOS-2670: Allow upgrades with the Plesk control panel
- CLOS-2707: Allow upgrades with the DirectAdmin control panel and add DirectAdmin rebuild to the post-elevation steps if it's installed
- CLOS-2759: Fix 'Cache-only enabled but no cache' errors for CLN repositories
- Add a built-in signature for Fedora EPEL packages

* Wed May 29 2024 Roman Prilipskii <rprilipskii@cloudlinux.com> - 0.16.0-9.cloudlinux
- CLOS-2631: Improve algorithm of overlayfs creation and disk space estimation
